### ISSUE TITLE
Move node-sass as peer dependency

### ISSUE THREAD

**Issue by colthreepv** [michaelwayman/node-sass-chokidar#1]
Sounds like a good idea?

Ideally that would be put in package.json with a `*` version, in order to let any node-sass version to be installed, and not worry about updating here every ver.

**Comment by michaelwayman** [comment]
my issue with moving `node-sass` to peerDependencies is that the user now has to manually install an acceptable version of node-sass themselves (if they don't already have it), an extra step that they need to take before everything is up and working.

node-sass-chokidar will always install the latest 4.x.x of node-sass (That's what the `^` means in the dependencies). You're right though, once 5.0.0 comes out, node-sass-chokidar will need updated, but a switch to peerDependencies doesn't guarantee NSC wouldn't need updated anyway (5.0.0 might have breaking changes)

So it's a tradeoff, but for now I am inclined to keep it how it is unless you can make a good argument why *WE HAVE TO SWITCH TO PEER DEPENDENCIES*
