### ISSUE TITLE
Imported partials aren't being watched for changes

### ISSUE THREAD

**Issue by modkaffes** [michaelwayman/node-sass-chokidar#10]
Using `node-sass` via an npm script I tell it to watch `app/assets/stylesheets/backend.scss` which is an entry file containing only imports (eg. `@import 'backend/base/variables'; @import 'backend/base/helpers';`, etc.) and upon changes in the imported files the watch event gets fired and styles get built in the assigned output directory.

However, this doesn't happen with `node-sass-chokidar`. Is this known behavior?

For reference here's my `node-sass` command:
```bash
node-sass app/assets/stylesheets/backend.scss --output public/assets/stylesheets --watch --recursive --source-map-embed --source-map-contents --include-path vendor/assets/stylesheets
```

**Comment by michaelwayman** [comment]
Thanks for bringing this up @modkaffes. I will look into this tonight, and see about getting it resolved ASAP.

`node-sass` only watches files that are part of a scss dependency graph leaving it unable to transpile newly created files without restarting.
`node-sass-chokidar` fixed this but must be accidentally ignoring part of the dependency graph in the process.

This should just be a small adjustment to node-sass-chokidar to watch the full dependency graph and not just part of it. Will let you know in a bit.

**Comment by michaelwayman** [comment]
OK this should be on npm `v0.0.3` let me know if this fixes the problem. If not I can reopen the issue and take a closer look.

**Comment by thepuzzlemaster** [comment]
I am running into this issue. Just set up a project, and am running the following script:
`"watch:css": "node-sass-chokidar --include-path node_modules/ src/Styles/Scss --output src/Styles/Css --watch --recursive",`

It works fine any time I save my Main.scss file. But if I make any changes in an imported partial file (_otherStyles.scss), it doesn't recompile. If I then make a change to Main.scss again, it recompiles the css and includes the previous change in _otherStyles.scss in the output. I'm on v1.5.0.

I'm really confused by this.
If it's helpful, I also ran into a weird issue with node-sass, where it would only recognize the first change to my imported files and none of the subsequent changes.

**Comment by thepuzzlemaster** [comment]
Oh my! I figured it out! It's a little crazy, but it's case sensitivity. I had a typo in my import, where instead of `@import 'otherStyles';` I had `@import 'otherstyles';`

So it still works fine as an import, but the watcher failed to watch it.

🤦 
Totally my fault, but a kind of strange behavior where it worked in the one way, but not the other led me astray.
