### ISSUE TITLE
News on update for node-sass 5 -> Node 15+

### ISSUE THREAD

**Issue by emish89** [michaelwayman/node-sass-chokidar#106]
Hi all,
There is the plan to release a version with node-sass 5 to be compatible with Node 15?
Thanks a lot

**Comment by carantunes** [comment]
Is there plans to release a version compatible with node 16? 

Everyone is dropping support for python 2 and this package still requires node-sass@"^4.14.1"  which uses node-gyp@"^3.8.0", which in place uses python2 :/

**Comment by anpriyadar** [comment]
Hi @michaelwayman can you please update the package to be used with new version of node js. There seems already a pull request for the same

**Comment by michaelwayman** [comment]
Version 2.0 now uses node-sass 7.0.1
