### ISSUE TITLE
cant watch my less files

### ISSUE THREAD

**Issue by pedropcruz** [michaelwayman/node-sass-chokidar#16]
Hello, so i will start to show how i organize my files (with the create-react-app bundle)

> /src
> ---/css
> -------/components
> ------------*.less files
> -------/elements
> ------------*.less files
> -------/main.less (this imports all my files on subdirectories)
> ---/img
> ---/js
> ---index.js
> package.json

And on my package, on "scripts" i have this:

```
...
"build-css": "node-sass-chokidar src/css/main.less -o public/",
"watch-css": "npm run build-css && node-sass-chokidar src/css/main.less -o public/ --watch --recursive",
...
```

Can't understand what i am doing wrong. i already tried with `**/*.less` and with `*.less ` and that never results. And the output i want as "main.css" on my public folder.

Many thanks,

Pedro Cruz

**Comment by pedropcruz** [comment]
You can close, this supports sass, not less

thanks anyway!

**Comment by michaelwayman** [comment]
> this supports sass, not less

That is correct.
I hope you find something that suits your needs!

**Comment by davidsonsns** [comment]
For this, I'm using [node-less-chokidar](https://github.com/sampi/node-less-chokidar)
