### ISSUE TITLE
Node Sass Magic Importer

### ISSUE THREAD

**Issue by zz-james** [michaelwayman/node-sass-chokidar#18]
Hi

Am new to node, but an experienced developer, I would like to use node-sass-magic-importer with my create-react-app which uses node-sass-chokidar, on a scale of 1-10 how difficult do you think that is going to be?
e.g.
https://github.com/maoberlehner/node-sass-magic-importer/tree/master/packages/node-sass-magic-importer

Many thanks

James

**Comment by michaelwayman** [comment]
Hey James, this looks like I really cool package, thanks for sharing.
I am not sure of the difficulty of using both but I am not sure that it would be required.
node-sass-chokidar is for compiling sass to css, it doesn't seem like you need the css part if you are able to import the sass directly.
