### ISSUE TITLE
Build / compile files by priority (watch)

### ISSUE THREAD

**Issue by Puzo** [michaelwayman/node-sass-chokidar#19]
Hello,

I would like to build/compile some files before all others (like _vars etc.). How can I achieve that?

For example, I have some global files which holds some variables and so on:

**First load: src/index.scss**
This file contains all the imports (@import).

**Second load: src/components**
Here are different .scss files for each component.

**Current command (watch-css):**
`npm run build-css && node-sass-chokidar -w src/ -o src/ --recursive --output-style compressed`

**Comment by michaelwayman** [comment]
@Puzo there isn't a way to do this with the watch option.
However, a dependency graph is built during compile so order shouldn't matter.

I think the issue you are running in to is the file name `_vars`.
Files that begin with an `_` are not compiled by node-sass or node-sass-chokidar.
If you remove the `_` then this might fix your issue.
