### ISSUE TITLE
Doesn't seem to compile new files?

### ISSUE THREAD

**Issue by JemarJones** [michaelwayman/node-sass-chokidar#21]
When running this with the recommended command from create-react-app,

```
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
```
, it doesn't seem to notice and compile newly created scss files. I have to cancel and re-run the command to get new files compiled.

**Comment by michaelwayman** [comment]
I'm pretty sure it does.. Can you please attach a VERY SMALL example project that duplicates your issue and include info such as (operating system, node version, node-sass-chokidar version, etc)

**Comment by michaelwayman** [comment]
Can you please share the version you are using, system you are on, and steps to reproduce?
It would go a long way to helping me resolve this.

**Comment by PaulRBerg** [comment]
Indeed, it doesn't compile new files. I'm afraid I cannot share my code, but I'm running Sierra 10.12.6 and I use `yarn start`. I've tried with `npm` and the result is the same.

**Comment by PaulRBerg** [comment]
I think I found a pattern. Whenever I have some warnings, the edited files aren't compiled. Could you investigate this?

**Comment by GreenAsJade** [comment]
Is there some reason why the watch command has --recursive whereas the build one doesn't have --recursive?

**Comment by michaelwayman** [comment]
@GreenAsJade `--recursive` doesn't actually do anything and has been removed.

Also, sorry for the delay, but I just published **version 1.0.0** and this should be fixed now.

Also, @JemarJones when you use the --watch option all the files are built at the beginning so you shouldn't need to
`"watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",`
instead you should be able to just do
`"watch-css": "npm run node-sass-chokidar src/ -o src/ --watch",`

**Comment by lmorchard** [comment]
FWIW, I have this issue too. On Windows, using node-sass-chokidar v1.3.3. I have a `watch:css` script in my package.json like this:

```
    "watch:css": "node-sass-chokidar src/ -o src/ --watch"
```

But, when I add a new `.scss` file somewhere under `src/` - it never gets picked up for processing until I stop the process and re-run it. From then on, changes are picked up.

**Comment by jozefmery** [comment]
Same behavior as Imorchard described, same setup, doesn't work.

**Comment by kylebebak** [comment]
I don't know how `node-sass-chokidar` works, but if it's just a wrapper around `node-sass`, perhaps it's related to <https://github.com/sass/node-sass/issues/1891>.

This bug seems to never have been fixed.
