### ISSUE TITLE
change files throw error status 3

### ISSUE THREAD

**Issue by hehehai** [michaelwayman/node-sass-chokidar#22]
``` shell
yarn run v1.1.0
$ node-sass-chokidar src/ -o src/ --watch --recursive
=> changed: G:\webDev\fullStack\node-sass-test\src\xx.scss
{
  "status": 3,
  "message": "File to read not found or unreadable: G:/webDev/fullStack/node-sass-test/src/xx.scss",
  "formatted": "Internal Error: File to read not found or unreadable: G:/webDev/fullStack/node-sass-test/src/xx.scss\n"
}
=> changed: G:\webDev\fullStack\node-sass-test\src\xx.scss
Rendering Complete, saving .css file...
Wrote CSS to G:\webDev\fullStack\node-sass-test\src\xx.css
```
```
node v8.6.0
yarn v1.1.0
"node-sass-chokidar": "^0.0.3"
```

first save modified file, throw error, again save file, that ok

😓

**Comment by michaelwayman** [comment]
I definitely see an issue of mixing the file paths, some parts are using forward slashes, other are using backslashes...

Are you on windows running docker or virtual box or something?

**Comment by hehehai** [comment]
Sorry, I find this is an editor's problem, but why I don't know。

like [node-sass-chokidar/issues/14](https://github.com/michaelwayman/node-sass-chokidar/issues/14)

I used VSCode, and I used node-sass-chokidar's watch to do the same after the last few days. I don't know what happened, so I use atom now.

Because of the problem of ability, there is no quick elimination of the problem, delay your time.
I'm sorry!

**Comment by xxDukeMCxx** [comment]
Hi,

Have the same problem with VSCODE. 
Read a lot of issues here and there about the fact that Chokidar detect the file change before VSCODE unlock it. Not a expert at all, but find that add the "--usePolling" param can help with VSCODE (error still raise, but a lot less).
Exemple : 
![image](https://user-images.githubusercontent.com/38319680/39624869-3281c85e-4f9b-11e8-8b8e-753fdda06072.png)

**Comment by marcosbozzani** [comment]
I've created a PR that fix this problem: https://github.com/sass/node-sass/pull/2386

If want to try this fix, you can patch your node-sass local copy replacing 'node_modules/node-sass/lib/render.js' with this version: https://github.com/marcosbozzani/node-sass/blob/bug-vscode-watch/lib/render.js

The diff is here: https://github.com/marcosbozzani/node-sass/commit/266861bf5761dcafd5d53d123264b965c861887c#diff-a485abf5b8f49de7f313d7799df3faf4

**Comment by yusriyunus** [comment]
> 
> 
> I've created a PR that fix this problem: [sass/node-sass#2386](https://github.com/sass/node-sass/pull/2386)
> 
> If want to try this fix, you can patch your node-sass local copy by replacing 'node_modules/node-sass/lib/render.js' with this version: https://github.com/marcosbozzani/node-sass/blob/bug-vscode-watch/lib/render.js
> 
> The diff is here: [marcosbozzani/node-sass@266861b#diff-a485abf5b8f49de7f313d7799df3faf4](https://github.com/marcosbozzani/node-sass/commit/266861bf5761dcafd5d53d123264b965c861887c#diff-a485abf5b8f49de7f313d7799df3faf4)

that works, awesome!

**Comment by yusriyunus** [comment]
@marcosbozzani that works, awesome!

**Comment by roeljohn** [comment]
sometimes I deleted the css folder because everytime you run sass it will generate css folder and css file but if it's doesn't work just use --usePolling like xxDukeMCxx above/
![usepolling](https://user-images.githubusercontent.com/8347743/57983586-44345f00-7a86-11e9-9d50-3866ecb7e487.JPG)

**Comment by marcosbozzani** [comment]
A ready to use patch of my fix is available here: https://github.com/marcosbozzani/patch-node-sass-watch
