### ISSUE TITLE
Functions not compiled

### ISSUE THREAD

**Issue by 3dos** [michaelwayman/node-sass-chokidar#23]
Hi there,

I bootstraped a create-react-app project with node-sass-chokidar as the CRA documentation recommends (with file watching) It works great with vars but doesn't seem to compile function and renders them "as is" in the output css file

Exemple : 
App.scss
```
.App-header {
  background-color: $background;
  color: $secondary-color;
}

.App-logo {
  height: rem-calc(85);
}
```

generated App.css
```
.App-header {
  background-color: #fff;
  color: #000; }

.App-logo {
  height: rem-calc(85); }
```

I guess I'm doing something wrong or forgot something but I can't manage to find what it is.

**Comment by hehehai** [comment]
I have also encountered the same problem

**Comment by michaelwayman** [comment]
`rem-calc` is not a built in sass function. Can you please submit all the code required to test with this?

**Comment by 3dos** [comment]
Oh well, I didn't know. I added foundation mixins to fix my issue. Thank you very much for your help.
