### ISSUE TITLE
Heroku not compiled

### ISSUE THREAD

**Issue by PaulRBerg** [michaelwayman/node-sass-chokidar#28]
This might be related to `node-sass` itself, but I don't know for sure. I simply cannot build the project for Heroku. Of course, I don't necessarily need the sass compiler on the server, I can simply push the `css` and ignore the `scss`, but it's quite annoying to go to `package.json` everytime to remove the `devDependencies` and the others.

```
Error: Cannot find module 'set-blocking'
remote: npm ERR! errno 1
remote: npm ERR! node-sass@4.6.1 install: `node scripts/install.js`
```

**Comment by michaelwayman** [comment]
I'm not quite sure what the issue you are having is or how it relates to node-sass or node-sass-chokidar. If You are deploying to heroku I don't think you should be installing any of the dev-dependencies.

Can you please describe how this relates to node-sass-chokidar and how I can help?
