### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/src'

### ISSUE THREAD

**Issue by dalevfenton** [michaelwayman/node-sass-chokidar#3]
Following the instructions running this with create-react-app I'm getting the following error only when running the watch script, the build script works properly.

As anyone can attest, having to manually run the build every time you make a change is pretty tedious so I'd like to get the watch script working properly.

As you can see in the screenshot when running the build command it properly finds the two .scss files, processes and saves them, subsequently when it finds files changed it processes each in turn but when trying to write the new .css file it throws

Error: EACCES: permission denied, mkdir '/src/'

When googling the error it appears as though this is usually about permissions with npm global modules. The thing I don't understand is why the build script would work, but the watch script ends up Erroring out.

<img width="717" alt="screen shot 2017-05-15 at 5 28 59 pm" src="https://cloud.githubusercontent.com/assets/16996057/26080469/c1ef949e-3994-11e7-920d-4933be284087.png">

**Comment by michaelwayman** [comment]
Did you install `node-sass-chokidar` as a global package or as a local?
This is definitely a permissions issue, I'll need to investigate the user and file permissions, but I actually have the flu right now so it's gunna take me a few days to get around to it, apologies.

**Comment by dalevfenton** [comment]
I figured out my mistake, I typed the command in as 

`npm run build-css && node-sass-chokidar src/ -o /src/ --watch --recursive`

if you'll look closely you'll see that I had an extra `/` at the start of the destination directory so it was trying to write to the root of the filesystem (even if I had had permissions it might have been tough to track down)

I had it correctly typed in the build command to place it in the `src/` directory relative to the project so that's why that was working. No issue to fix, just my bad typing.
