### ISSUE TITLE
Files are not initially compiled when using --watch, only when changes occur while watching

### ISSUE THREAD

**Issue by RoyTinker** [michaelwayman/node-sass-chokidar#31]
To repro, run the following with a single .scss (uncompiled) file under `./src`
`node-sass-chokidar ./src -o ./src --source-map true --watch`
=> Notice the file is not compiled.

Now make a change to the file, notice it is compiled.

Workaround is to run `node-sass` in non-watch mode prior to `node-sass-chokidar`:
`node-sass ./src -r -o ./src --source-map true && node-sass-chokidar ./src -o ./src --source-map true --watch`

**Comment by michaelwayman** [comment]
This is not a bug but the actual intended behavior. Let's say that we are watching a folder with hundreds of scss files in it that have already been compiled, we don't want to waste the time and resources recompiling all of them.

For large scale projects in mind, monolithic projects the extra start-up time could be annoying. I believe node-sass is the same behavior for I imagine the same reason.

**Comment by RoyTinker** [comment]
@michaelwayman Makes sense, thanks.

**Comment by michaelwayman** [comment]
@RoyTinker it makes sense, but I went ahead and did it anyway for you lol. Version 1.0.1 will have the behavior we discussed. 👍

**Comment by RoyTinker** [comment]
Haha ok @michaelwayman :-)
