### ISSUE TITLE
Is it possible to change the npm name?

### ISSUE THREAD

**Issue by crazyyi** [michaelwayman/node-sass-chokidar#32]
This library is cool and is recommended by many. But every time I want to add it to npm I forget its name. Can you change it to something easier to remember?

**Comment by michaelwayman** [comment]
The name _chokidar_ refers to how this project is different than _node-sass_. Where chokidar is a file system watcher that is better than the one used by node-sass. I'm sorry that chokidar is hard to remember but at this point with it being used in so many projects it isn't likely going to change unless the entire community wants it.

Perhaps if you Star the project, or Favorite it, or write it down, (I'm being serious) but with thousands of downloads per day I can't just rename the project and leave all those people wondering why their project suddenly won't work.
