### ISSUE TITLE
Constantly getting "Undefined variable"

### ISSUE THREAD

**Issue by borisyordanov** [michaelwayman/node-sass-chokidar#33]
I have an issue with a React app.
It's built with create-react-app and SASS has been added according to [this guide](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)

Here is the package.json
```
  "dependencies": {
    "axios": "^0.17.1",
    "bootstrap": "4.0.0-beta.2",
    "currency-formatter": "^1.3.1",
    "firebase": "^4.6.2",
    "money": "^0.2.0",
    "node-sass-chokidar": "0.0.3",
    "npm-run-all": "^4.1.2",
    "rand-token": "^0.4.0",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-html-email": "^3.0.0",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "react-scripts": "1.0.17",
    "reactstrap": "5.0.0-alpha.4",
    "redux": "^3.7.2",
    "redux-form": "^7.1.2",
    "redux-i18n": "^1.5.10",
    "redux-thunk": "^2.2.0"
  },
  "scripts": {
	"build-css": "node-sass-chokidar src/ -o src/",
	"watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "react-scripts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
```
I am trying to make [this template](https://github.com/mrholek/CoreUI-React) run on my app. Here is my file/folder structure:
![image](https://user-images.githubusercontent.com/12392666/34391819-c8fe9a3c-eb50-11e7-9bcf-bb8ce5a4d133.png)

The only difference from the template's architecture is that i put all the styling in a `styles` folder, instead of `scss` and [this](https://gist.github.com/borisyordanov/6c5a489d34d8f01c373abb094e0245eb) is the component which imports the css.

[This](https://gist.github.com/borisyordanov/052cb4aca744f862518c2febd54f3263) is what happens when i try to build the project.

I keep getting a missing variable although the variables are loaded before the scss that errors out.

```
// Override Boostrap variables
@import "bootstrap-variables"; //variables that i need to run the app

// Import Bootstrap source files
@import "../../../../../node_modules/bootstrap/scss/bootstrap.scss"; //variables that i need to run the app

// Override core variables
@import "core-variables";

// Import core styles
@import "core/core"; //files that can't find the variables that are imported above

// Custom styles
@import "
```
How can i remedy this?

I'm running Windows 10 and Node v7.7.3. I'd also like to point out that i am using the same template on another app build with create-react-app and setup to use SASS and do not have this problem.

I setup a [repo](https://github.com/borisyordanov/node-sass-bug), that you can pull, run `npm install` and then try `npm start` to reproduce the issue.

**Comment by littletower** [comment]
same here. variables are not found when importing them from another file. 
But they are found on ‘watch‘.
I'm running v8.9.1

**Comment by borisyordanov** [comment]
@littletower I have an update on this bug, i was sent [this](https://github.com/ShaneMckenna23/react-help), but haven't investigated further, let me know if it helps you.

**Comment by littletower** [comment]
thanks @borisyordanov, I'll check this out!

**Comment by AlbertoAbruzzo** [comment]
Same here. Solutions?

**Comment by littletower** [comment]
I just put all my variables in a separate file and imported it in every stylesheet that used those variables. That worked for me, even though it's certainly not the cleanest solution...

**Comment by AlbertoAbruzzo** [comment]
Ok, found a solution, this is from create-react-app [repo](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc):

```
"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
```

for my use case i changed it like this and got working:

```
"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/App.scss -o src",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules --watch src/App.scss src/App.css",
```

**Comment by michaelwayman** [comment]
@borisyordanov is this still an issue or can I close this?

It it's still an issue, what is the exact error output that you are getting?

**Comment by borisyordanov** [comment]
This bug was indeed caused because of the order that files are imported, changing the file structure or build sequence can help fix that. It's not an issue with `node-sass-chokidar`, just poor understanding of the build process from my side!
