### ISSUE TITLE
Sass files deeper than 2 folders are not watched.

### ISSUE THREAD

**Issue by balazsorban44** [michaelwayman/node-sass-chokidar#35]
I recently updated a React project to use Sass. I used the following scripts in my `package.json`:

```
"build-css": "node-sass-chokidar --include-path ./src/sass src/sass/main.sass src/main.css",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src/sass src/sass/main.sass src/main.css -w -r",
"start-js": "react-scripts start",
"start": "npm-run-all -p watch-css start-js",
```

It looks like that sass files which are deeper than 2 in a folder structure are not watched, and when I change them nothing is compiled.

**Comment by bsubedi26** [comment]
@balazsorban44, Try this.

**Comment by balazsorban44** [comment]
@bsubedi26 In theory, I wouldn't even need any flags because it is set to true as default. But I tried, and it is not working either.

**Comment by balazsorban44** [comment]
I was not using quotes in my imports, which caused those files not being watched somehow.

```import '1-essentials/main'```
Instead of
```import 1-essentials/main```
solved my issue.
