### ISSUE TITLE
how to compile multiple sources

### ISSUE THREAD

**Issue by heinhoang** [michaelwayman/node-sass-chokidar#37]
I want to compile scss from folder src1 to target1 and src2 to target2. How to do that?

**Comment by michaelwayman** [comment]
You should be able to run 2 instances of node-sass-chokidar at the same time. You'll just need to have 2 terminals running at the same time. I don't believe there is another way

**Comment by heinhoang** [comment]
Thanks, if that's the only way I think we can use `concurrently` to run the commands as parallel tasks:
```
"watch": "concurrently -k \"node-sass-chokidar src1/ -o target1/ --watch\" \"node-sass-chokidar src2/ -o target2/ --watch\""
```
