### ISSUE TITLE
try to watch eslintrc 

### ISSUE THREAD

**Issue by eMerzh** [michaelwayman/node-sass-chokidar#46]
Hi, 
i was trying to integrate node-sass-chokidar to my CRA app,

when i launch `node-sass-chokidar --include-path ./node_modules src/ -m *.scss -o src/`

everything works as expected, it compiles.

if i add the watch 
`node-sass-chokidar --include-path ./node_modules src/ -m *.scss -o src/ --watch`
or 
`node-sass-chokidar --include-path ./node_modules src/ -m *.scss -o src/ --watch -m '*.scss' `
it seems to try to compile eslintrc in css 🤔 .

here is +- the output:

```
=> changed: path/to/src/1.scss
=> changed: path/to/src/2.scss
=> changed: path/to/src/3.scss
Rendering Complete, saving .css file...
Rendering Complete, saving .css file...
Rendering Complete, saving .css file...
Wrote CSS to  path/to/src/1.css
Wrote CSS to  path/to/src/2.css
Wrote CSS to  path/to/src/3.css
```
then , (first line in gray, rest in red) : 
```
=> changed: /path/to/src/.eslintrc
{
  "status": 1,
  "file": "path/to/src/.eslintrc",
  "line": 1,
  "column": 1,
  "message": "Invalid CSS after \"{\": expected 1 selector or at-rule, was \"{\"",
  "formatted": "Error: Invalid CSS after \"{\": expected 1 selector or at-rule, was \"{\"\n        on line 1 of src/.eslintrc\n>> {\n   ^\n"
}
```

**Comment by michaelwayman** [comment]
Wow that is weird.
I am not able to duplicate this, at all.
Can you please a project that is able to duplicate the issue.

**Comment by eMerzh** [comment]
unfortunatly no :/ it's a private project, but i'll try to make a reduce it to a thing i can share.
FWIW i'm using yarn 1.5.1 , node v9.8.0 and latest version of node-sass-chokidar (not master though)

**Comment by eMerzh** [comment]
thanks for your patience here :)
so i tracked it down to this guy:
https://github.com/michaelwayman/node-sass-chokidar/blob/master/bin/node-sass-chokidar#L266

which add in the paths this : `/Users/myUser/Code/my-project/src/**/*.{sass,scss}` 
which looks good but if i comment this line, everything is fine :)

**Comment by eMerzh** [comment]
seems a chokidar issue.. i did  : 

```js 
var chokidar = require('chokidar');

chokidar.watch('src/**/*.{sass,scss}').on('all', (event, path) => {
  console.log(event, path);
});
```

and it give me  
```
add src/common.scss
add src/setup.scss
add src/.eslintrc
```

**Comment by michaelwayman** [comment]
I make a project to _try_ and duplicate this issue, I but I am unable to duplicate it...

 [project](https://github.com/michaelwayman/test-chokidar)

The output of the script you provided.
```
> node index.js                                                           
add src/setup.scss
add src/common.scss
^C
```

## REGARDLESS
Since this appears to be a chokidar issue, and not a node-sass-chokidar issue, I am closing it here.
