### ISSUE TITLE
Add parameter for setting "interval of polling" for Chokidar

### ISSUE THREAD

**Issue by xxDukeMCxx** [michaelwayman/node-sass-chokidar#53]
Hi,

For better compatibilty with some text editor (see #22 and #14 ), could you add the possiblity of setting by parameter the interval of polling for Chokidar ?

Exemple : 
![image](https://user-images.githubusercontent.com/38319680/39626839-e72b07b8-4fa3-11e8-8f3c-b63e7468919e.png)

Currently, it seem's that only thoses 3 parameters can be transfert from node-saas-chokidar to the chokidar watcher : 
![image](https://user-images.githubusercontent.com/38319680/39626883-12523af6-4fa4-11e8-9b1b-db05b8abca2e.png)

----
optionnaly/alternatively , cause my issue is with React, perhaps add the dotenv support so node-sass-chokidar can automatically "usePolling" when the React project is set to "usePolling" from .env configuration ( https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration )

i try it loccaly by just add the 
` require('dotenv').config();`
at beggining of your script, and it work well, so i can set usePolling AND interval by a simple .env file : 
![image](https://user-images.githubusercontent.com/38319680/39627820-5aa807ec-4fa7-11e8-95cf-21f88207b062.png)
 

thanks for all,
bests regards,

**Comment by michaelwayman** [comment]
ok this should be fixed in db94130 and in `node-sass-chokidar@1.3`
