### ISSUE TITLE
How to use --source-map-root correctly?

### ISSUE THREAD

**Issue by shawnwithlegion** [michaelwayman/node-sass-chokidar#54]
Here is my command line: `node-sass-chokidar --source-map-embed --quiet --watch --output ./webpack-css --source-map-root file://${PWD}/ --source-map true ./app/scss/main/app.scss`

I ran this under /Users/me/Desktop/my-project. However, every source map is prepended with only /Users/me/Desktop/.

/my-project is missing somehow. How can I fix it?

**Comment by michaelwayman** [comment]
I'm not 100% sure what you're issue is, but here is an example of using `--source-root-map`

`node-sass-chokidar --include-path ./node_modules ./src -o ./src --source-map-root ./src --source-map true --source-map-embed`

after running that `./src/app.css.map` gets created with the source map. Does this help?

**Comment by shawnwithlegion** [comment]
It helps. Thanks!
