### ISSUE TITLE
Vulnerability in Hoek dependency from npm audit 

### ISSUE THREAD

**Issue by TmNguyen12** [michaelwayman/node-sass-chokidar#58]
https://nodesecurity.io/advisories/566

Current dependency is hoek 2.16.3. It's patched in version 5.0.3. Can we update this version of hoek int the dependency? 

Thanks!

**Comment by asonni** [comment]
As well as `tunnel-agent` dependency https://nodesecurity.io/advisories/598

Thanks!

**Comment by mvallerie** [comment]
+1 for this. Thanks in advance.

**Comment by jbwyatt4** [comment]
+1 also for this. Commenting to raise awareness. Thanks in advance.

**Comment by henning-kvinnesland** [comment]
It seems there's a whole chain of sub-dependencies blocking this issue. As far as I can tell, we should direct our attention here: https://github.com/nodejs/node-gyp/pull/1492.

**Comment by michaelwayman** [comment]
OK I did an audit and the only vulnerabilities are from node-sass which node-sass-chokidar depends on, so until they can resolve on their end then there isn't much to do. but I assure you none of the vulnerabilities are high-priority
