### ISSUE TITLE
Uknown variables and Mixins

### ISSUE THREAD

**Issue by michalica** [michaelwayman/node-sass-chokidar#59]
I am using create react app with SASS.

**My file structure:**
-styles
--variables.scss
--mixins.scss
--main.scss
-v2-styles
--stylesWhereAreMixnsAndVariablesUsed.scss
-App.scss

**App.scss:**
@import 'styles/main.scss'; // includes all .scss files from .styles/ folder
// other styles from ./v2-styles

After updating node-sass-chokidar from 0.0.3 to 1.0.1 or higher I have issue when  I run build-css "all variables and mixins are undefined" but watch-css works good.

"message": "Undefined variable: \"$text-color\".",
 "formatted": "Error: Undefined variable: \"$text-color\".\n 

my scripts:
`"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules  -o src ./src/App.scss",`
`"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --src/App.scss src/App.css"`

**Comment by michaelwayman** [comment]
You no longer need to run build-css in watch-css. perfects looking at the usages a little closer and you read the help pages and you mind find the issue.
