### ISSUE TITLE
omitted asterisk from  "&:not(*:root)" at build 

### ISSUE THREAD

**Issue by logic17** [michaelwayman/node-sass-chokidar#60]
Hi, 
I want to differentiate between Chrome and all other browsers. 
So I use this hack as a css selector: 
&:not(*:root) {
***** content here *****
}

It works in dev (localhost), but not in prod (build),
when I look in the css I see Chokidar has omitted the '*' from the selector:
 &:not(:root).

Please help me to avoid this behavior.

**Comment by michaelwayman** [comment]
This is not the correct way to go about this, instead you should use the sass features to be all browser compliant. Look at the sass website and mixing for examples
