### ISSUE TITLE
Please update hoek and tunnel-agent

### ISSUE THREAD

**Issue by jbwyatt4** [michaelwayman/node-sass-chokidar#61]
Hi,

NPM reports 9 vulnerabilities fixed in the latest versions of the above packages.

**Comment by henning-kvinnesland** [comment]
I totally agree and I'm awaiting this impatiently, but this is a duplicate of https://github.com/michaelwayman/node-sass-chokidar/issues/58.

**Comment by jbwyatt4** [comment]
Ah, closing the issue and following above.
