### ISSUE TITLE
Bug in directory loop  

### ISSUE THREAD

**Issue by jimzezz** [michaelwayman/node-sass-chokidar#93]
In https://github.com/michaelwayman/node-sass-chokidar/commit/c34bf7ed35634c35cfc56a5dab2562d33010f817 a check was added to skip files not matching a provided regexp but this causes the loop to stall indefinitely (or exit?) if a file is skipped. Not sure why the process doesn't hang but this causes subsequent files to not be processed.

Looks like this should just be a matter of moving the `done` listener inside the if condition, i.e

```
forEach(files, function(subject) {
  if (passesRegex(options, subject)) {
    emitter.once('done', this.async());
    renderFile(subject, options, emitter);
  }
}
```

**Comment by bill-oneil** [comment]
In my project, my css classes is overwriten by node_module css classes. Is this because recursive problem?
