### ISSUE TITLE
subDirectory css classes is overwrited by node_modules css classes

### ISSUE THREAD

**Issue by bill-oneil** [michaelwayman/node-sass-chokidar#96]
The classes that is defined in subDirectory css file is overwrited by node_module css classes.
In browser dev inspect environment, node_module css classes is over than programmer's css classes.

**Comment by michaelwayman** [comment]
Could you please provide a small sample of this and I will make the fix and release it ASAP?

**Comment by bill-oneil** [comment]
Thanks for your kind. The problem is solved.
