### ISSUE TITLE
Support for Node 14 (chokidar 3)

### ISSUE THREAD

**Issue by sapanju** [michaelwayman/node-sass-chokidar#97]
I'm upgrading my app to use node 14, which requires updating the deprecated chokidar 2 to chokidar 3. See:
https://www.npmjs.com/package/chokidar/v/2.0.4

 However, I'm unable to do so because I use `node-sass-chokidar` and the latest version of this package still depends on chokidar 2.

Can we get a version with the updated dependency?

**Comment by michaelwayman** [comment]
I am releasing this over this weekend.

**Comment by michaelwayman** [comment]
DId the latest release fix this problem https://www.npmjs.com/package/node-sass-chokidar?
V 1.5.0?

**Comment by sapanju** [comment]
Yes, it did! Thank you. We can close this.

**Comment by mwayman** [comment]
TY :) 

I don't maintain this repo that often but I've made it a personal goal to get to everyone's issues over the next week or two resolved. (I'm busy with an actual job otherwise I'd move faster)
